---

num_rounds: 50
num_clients: 13
batch_size: 32
num_classes: 2
num_clients_per_round_fit: 13
num_clients_per_round_eval: 13
config_fit: 
  lr: 0.01
  momentum: 0.9
  local_epochs: 20

model: 
  _target_: centralized.Net

defaults: 
  - strategy: fedavg
  - model: net
  #- client: fedbn