---

num_rounds: 20
num_clients: 25
batch_size: 16
num_classes: 2
num_clients_per_round_fit: 25
num_clients_per_round_eval: 25
config_fit: 
  lr: 0.01
  momentum: 0.9
  local_epochs: 20

model: 
  _target_: centralized.Net

defaults: 
  - strategy: fedavg
  - model: net
  #- client: fedbn